INSERT INTO product (name,price) VALUES ('Teste 1', 22.2);
INSERT INTO product (name,price) VALUES ('Teste 2', 23.2);
INSERT INTO product (name,price) VALUES ('Teste 3', 25.2);
INSERT INTO product (name,price) VALUES ('Teste 4', 600.0);
INSERT INTO product (name,price) VALUES ('Teste 5', 152.69);
INSERT INTO customer (name,email) VALUES ('Fulano', 'fulano@email.com');
INSERT INTO customer (name,email) VALUES ('Ciclano', 'ciclano@email.com');
INSERT INTO customer (name,email) VALUES ('Beltrano', 'beltrano@email.com');
--INSERT INTO orders (customer_id,date_created) VALUES (1, CURRENT_DATE);
--INSERT INTO order_item (quantity,ORDER_ID ,PRODUCT_ID ) VALUES (2, 1, 1);
--INSERT INTO order_item (quantity,ORDER_ID ,PRODUCT_ID ) VALUES (3, 1, 2);